---
- hosts: all
  become: yes

  vars:
    nfcmusik_run_user: nfcmusik-run
    nfcmusik_run_group: nfcmusik-run
    nfcmusik_home: /usr/local/nfcmusik

  pre_tasks:
    - name: Update requirements.txt
      shell: pipenv --bare lock --requirements > requirements.txt
      args:
        chdir: "{{ playbook_dir }}/../.."
      delegate_to: localhost
      become: no

    - name: Archive your current git workspace as preparation for installation within the image
      command: git archive --format=tar --output build/nfcmusik-git-repo.tar HEAD
      args:
        chdir: "{{ playbook_dir }}/../.."
      delegate_to: localhost
      become: no

  tasks:
    - name: Install packages required to build the python app
      apt:
        name:
          - gcc
          - git
          - libsdl1.2-dev
          - libfreetype6-dev
          - libsdl-mixer1.2-dev
          - libsdl-image1.2-dev
          - libsdl-ttf2.0-dev
          - libjpeg-dev
          - libpng-dev
          - libportmidi-dev
          - python3
          - python3-dev
          - python3-pip
        state: present

    - name: Create nfcmusik run group
      group:
        name: "{{ nfcmusik_run_group }}"
        system: yes
        state: present

    - name: Create nfcmusik run user
      user:
        name: "{{ nfcmusik_run_user }}"
        comment: nfcmusik run user
        group: "{{ nfcmusik_run_group }}"
        groups: users,audio,video,plugdev,netdev,input,gpio,spi
        system: yes
        state: present

    - name: Create nfcmusik install dir
      file:
        path: "{{ nfcmusik_home }}"
        state: directory
        group: "{{ nfcmusik_run_group }}"
        mode: 0750

    - name: Transfer and unpack git archive
      unarchive:
        src: "{{ playbook_dir }}/../../build/nfcmusik-git-repo.tar"
        dest: "{{ nfcmusik_home }}"
        group: "{{ nfcmusik_run_group }}"

    - name: Install nfcmusik from the repository
      pip:
        requirements: "{{ nfcmusik_home }}/requirements.txt"
        executable: pip3

    - name: Create systemd service file
      template:
        src: nfcmusik.service.j2
        dest: /etc/systemd/system/nfcmusik.service
      notify:
        - nfcmusik-restart

    - name: Enable and start the service
      systemd:
        name: nfcmusik
        enabled: yes
        state: started
        daemon_reload: yes
      register: _nfcmusik_service_start

  handlers:
    - name: nfcmusik-restart
      when: not _nfcmusik_service_start is changed
      systemd:
        name: nfcmusik
        state: restarted
