---
- hosts: all
  become: yes

  tasks:
    - name: Install packages required to build the python app
      apt:
        name:
          - gcc
          - git
          - python3
          - python3-dev
          - python3-pip
        state: present
