---
- hosts: all
  become: yes

  vars:
    ap_cidr: 10.100.0.1/24
    ap_ssid: nfcmusik
    ap_channel: 7

  vars_prompt:
    - name: ap_password
      prompt: Choose a password for the access point's WIFI
      private: yes

  pre_tasks:
    - name: Install python-apt
      raw: apt -y update && apt install -y python-minimal python-apt python-setuptools
    - name: Install some base packages
      apt:
        name:
          - vim
        state: present
        update_cache: yes

  roles:
    - dhcpcd
    - hostapd
    - systemd-resolved
    - rpi-if-spi
