---
- name: Configure systemd-resolved
  template:
    src: pi-ap.network.j2
    dest: /etc/systemd/network/pi-ap.network
    owner: root
    mode: 0644
  notify:
    - networking-restart
    - systemd-resolved-restart
