---
- name: Providing the base
  include_tasks: preflight.yml

- name: Enable the relevant services
  systemd:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - systemd-networkd
    - systemd-resolved

- name: Configure systemd-resolved
  template:
    src: pi-ap.network.j2
    dest: /etc/systemd/network.d/pi-ap.network
    owner: root
    mode: 0644
  notify:
    - systemd-resolved-restart
    - systemd-networkd-restart