#cloud-config
# vim: syntax=yaml
#
hostname: nfcmusik
locale: en_US.UTF-8
manage_etc_hosts: true
package_upgrade: false
users:
  - name: nfcmusik-adm
    gecos: nfcmusik management user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,audio,video,plugdev,netdev,input,gpio,spi
    plain_text_passwd: nfcmusik
    lock_passwd: false