#cloud-config
# vim: syntax=yaml
hostname: nfcmusik
locale: en_US.UTF-8
manage_etc_hosts: true
package_upgrade: false
users:
  - name: nfcmusik
    gecos: nfcmusik service run user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,audio
    plain_text_passwd: nfcmusik
    lock_passwd: true
